version: 2.1

executors:
  circle-jdk-executor:
    working_directory: ~/rewrite-testing-frameworks
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    docker:
      - image: cimg/openjdk:11.0
  machine-executor:
    working_directory: ~/rewrite-testing-frameworks
    machine:
      image: ubuntu-1604:201903-01

commands:
  gradlew-build:
    description: 'Run a Gradle build using the wrapper'
    parameters:
      command:
        type: string
        default: 'check test'
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: downloadDependencies
          command: ./gradlew downloadDependencies
      - save_cache:
          key: gradle-dependencies-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle
      - run:
          name: run gradle command
          command: ./gradlew << parameters.command >>
      - run:
          name: collect test reports
          when: always
          command: |
            mkdir -p ~/rewrite-testing-frameworks/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/rewrite-testing-frameworks/test-results/junit/ \;
      - store_test_results:
          path: ~/rewrite-testing-frameworks/test-results/
      - store_artifacts:
          path: ~/rewrite-testing-frameworks/test-results/

jobs:
  build:
    executor: circle-jdk-executor
    steps:
      - gradlew-build

  deploy:
    executor: circle-jdk-executor
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ checksum "build.gradle.kts" }}
      - deploy:
          name: Deployment
          command: sh ./gradle/deploy.sh

workflows:
  version: 2
  build_prs_deploy_snapshots:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /\d+\.\d+\.x/
  build_deploy_releases:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
